// Write a function sum that finds the sum of two numbers. 
// Side quest - Try passing in a string instead of a number and see what happens?


function sum(a, b) {
    return a + b;
}

// Example Usage
console.log(sum(2, 3)); // Output: 5
console.log(sum('Rahul', 3)); // Output: '23' (string concatenation)
console.log(sum(2, 'Dadhich')); // Output: '23' (string concatenation)
console.log(sum('Hello', 'world')); // Output: '23' (string concatenation)
